{% set name = "reprimand" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wokast/RePrimAnd/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d72d4749d3c2087f9a231023d406bd4c30ea3c953d2a9f0a6c7780168d6c8d6d
  
build:
  skip: True  # [not linux]
  number: 6

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - meson 
    - ninja
    - pkg-config
  host:
    - libboost-python-devel
    - gsl
    - libblas
    - libcblas
    - hdf5
    - zlib
  run:
    - gsl
    - hdf5

test:
  imports:

  requires:

  commands:
    - test -f $PREFIX/lib/libRePrimAnd$SHLIB_EXT    
    - test -f $PREFIX/include/reprimand/eos_barotropic.h            


about:
  home: https://github.com/wokast/RePrimAnd
  summary: 'RePrimAnd library for neutron star related codes and GRMHD'
  description: |
    RePrimAnd is a C++ library providing: a framework for neutron star matter equations of state, functions
    for computing neutron star structure, tools for working with NS sequences, and a solution to the GRMHD 
    primitive recovery problem.
  license: CC-BY-SA-4.0
  license_file: LICENSE
  doc_url: https://wokast.github.io/RePrimAnd/index.html
  dev_url: https://github.com/wokast/RePrimAnd

extra:
  recipe-maintainers:
    - wokast
